apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: team11-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: log680
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "0.1"
            memory: "64Mi"  # Réduisez la limite de mémoire en fonction de vos besoins
          requests:
            cpu: "0.1"
            memory: "64Mi"  # Réduisez la demande de mémoire en fonction de vos besoins

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: team11-namespace
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP