name: CI

on:
  push:
    branches:
      - main  # Déclenche le pipeline uniquement sur la branche principale (main)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Remplacez par la version Python que vous utilisez

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install psycopg2

    - name: Run tests
      run: |
        python test/test.py
        exit 0

    - name: Lint and format code
      run: |
        pip install pylint black
        pylint src/main.py
        black --check src/main.py
