name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t log680gr11/oxygen:latest .
        docker build -t log680gr11/oxygen:1.0 .  # Ajoutez une étiquette avec la version 1.0
        docker push log680gr11/oxygen:latest
        docker push log680gr11/oxygen:1.0  # Poussez également l'image avec l'étiquette de version
